apiVersion: v1
kind: Service
metadata:
  name: device-registry
  namespace: iot-edge
  labels:
    app: device-registry
spec:
  type: ClusterIP
  selector:
    app: device-registry
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP
