apiVersion: v1
kind: Service
metadata:
  name: edge-gateway
  namespace: iot-edge
  labels:
    app: edge-gateway
spec:
  type: ClusterIP
  selector:
    app: edge-gateway
  ports:
    - name: http
      port: 8005
      targetPort: 8005
      protocol: TCP
